version: "3.9"
name: doitforme-project-mysql

services:
  mysql_sl_db:
    image: mysql:8.0.32
    restart: unless-stopped
    env_file: .env
    container_name: mysql_sl_db
    hostname: mysql_sl_db
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      # !Keep order of declaration, will init the data base with the dump at img creation
      # - vol_mysql_sl_db:/var/lib/mysql
      - ./src/data/data.sql:/docker-entrypoint-initdb.d/setup.sql

# Run all  : docker-compose up
# Stop all : docker-compose down
# Stop all and delte all img : docker-compose down --rmi all